name: ML Model CI with Retraining

# When should this workflow run?
on:
  push: # When you push code
    branches: [ main ] # To the main branch
  workflow_dispatch: # Allows you to manually run it from the Actions tab

jobs:
  train_test_retrain_pipeline: # Name of our job
    runs-on: ubuntu-latest # Use a standard Linux environment

    steps:
      # Step 1: Get your code from the repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can choose other versions like 3.9, 3.11

      # Step 3: Install the Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the initial training script
      # This ensures we always have a 'model.joblib' before testing starts
      - name: Run Initial Model Training
        run: python train.py

      # Step 5: Run the test script (which includes the retraining logic)
      # The test_model.py script will exit with 0 if successful, or 1 if it fails
      # after all retraining attempts. GitHub Actions uses this exit code.
      - name: Test Model (and Retrain if Needed)
        run: python test_model.py
